[phases.setup]
nixPkgs = ['python311', 'pkg-config', 'cmake']

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install --no-cache-dir torch==2.3.1+cpu torchvision==0.18.1+cpu --index-url https://download.pytorch.org/whl/cpu',
    'pip install --no-cache-dir --timeout=1000 -r requirements.txt'
]

[phases.build]
cmds = ['mkdir -p models static/uploads output_videos']

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --threads 2 app:app'

[variables]
PORT = '5000'
PYTHONPATH = '/app'